### ISSUE TITLE
Path Finding

### ISSUE THREAD

**Issue by akshitadixit** [akshitadixit/Structurex#4]
Addition of Path Finding algorithms preferably Djikstra and A*

**Comment by SuryanshNaugraiya** [comment]
hi akshita, i want to contribute in your project especially in this issue as i have created an end to end PathFinding project that uses bfs, a* and dijkistras algo to find the shortest path. but i can contribute only after 10 july because the program will start from 10.
so please assign this issue to me.

you can see the images of my project.
![Screenshot (237)](https://user-images.githubusercontent.com/53707393/124209792-d33a4f00-db07-11eb-9ba2-471b940f815c.png)
![Screenshot (236)](https://user-images.githubusercontent.com/53707393/124209796-d5041280-db07-11eb-8198-e74a7b1e5d23.png)

**Comment by akshitadixit** [comment]
@SuryanshNaugraiya that looks pretty cool! Sure you can work on this. Just remember to go with the current UI.

**Comment by SuryanshNaugraiya** [comment]
hi @akshitadixit , i was busy in the process of my placement activities, so i was not able to contribute, but now i am free, so i want to start the work, just tell me that if i can start the work? And if there are any formalities before starting the work that i have to complete?

**Comment by akshitadixit** [comment]
You can start away. No problems.

**Comment by SuryanshNaugraiya** [comment]
> You can start away. No problems.

@akshitadixit is there any project structure that i need to follow, or i can just simply upload it.

**Comment by akshitadixit** [comment]
Clone the repo on your local to find that for every menu item in the navbar, we have a different .html file that contains stuff, and javascript codes are arranged likewise.

**Comment by SuryanshNaugraiya** [comment]
@akshitadixit completed the work. please check it and merge it.
